export const GET_USER_PLAYLISTS_START =
  'app/Playlists/GET_USER_PLAYLISTS_START';
export const GET_USER_PLAYLISTS_SUCCESS =
  'app/Playlists/GET_USER_PLAYLISTS_SUCCESS';
export const GET_USER_PLAYLISTS_FAILURE =
  'app/Playlists/GET_USER_PLAYLISTS_FAILURE';

export const GET_PLAYLIST_START = 'app/Playlists/GET_PLAYLIST_START';
export const GET_PLAYLIST_SUCCESS = 'app/Playlists/GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_FAILURE = 'app/Playlists/GET_PLAYLIST_FAILURE';


export const GET_USER_TRACKS_START = 'app/Playlists/GET_USER_TRACKS_START';
export const GET_USER_TRACKS_SUCCESS = 'app/Playlists/GET_USER_TRACKS_SUCCESS';
export const GET_USER_TRACKS_FAILURE = 'app/Playlists/GET_USER_TRACKS_FAILURE';

export const CHECK_USER_FOLLOW_PLAYLIST_START =
  'app/Playlists/CHECK_USER_FOLLOW_PLAYLIST_START';
export const CHECK_USER_FOLLOW_PLAYLIST_SUCCESS =
  'app/Playlists/CHECK_USER_FOLLOW_PLAYLIST_SUCCESS';
export const CHECK_USER_FOLLOW_PLAYLIST_FAILURE =
  'app/Playlists/CHECK_USER_FOLLOW_PLAYLIST_FAILURE';

export const FOLLOW_PLAYLIST_START = 'app/Playlists/FOLLOW_PLAYLIST_START';
export const FOLLOW_PLAYLIST_SUCCESS = 'app/Playlists/FOLLOW_PLAYLIST_SUCCESS';
export const FOLLOW_PLAYLIST_FAILURE = 'app/Playlists/FOLLOW_PLAYLIST_FAILURE';

export const LIKE_SONG_START = 'app/Playlists/LIKE_SONG_START';
export const LIKE_SONG_FAILURE = 'app/Playlists/LIKE_SONG_FAILURE';

export const CHECK_LIKE_SONG_START = 'app/Playlists/CHECK_LIKE_SONG_START';
export const CHECK_LIKE_SONG_SUCCESS = 'app/Playlists/CHECK_LIKE_SONG_SUCCESS';
export const CHECK_LIKE_SONG_FAILURE = 'app/Playlists/CHECK_LIKE_SONG_FAILURE';

export const CLEAN_PLAYLIST = 'app/Playlists/CLEAN_PLAYLIST';

//AWS METODOS
//GET
export const GET_AWSUSER_PLAYLISTS_START =
  'app/Playlists/GET_USER_PLAYLISTS_START';
export const GET_AWSUSER_PLAYLISTS_SUCCESS =
  'app/Playlists/GET_USER_PLAYLISTS_SUCCESS';
export const GET_AWSUSER_PLAYLISTS_FAILURE =
  'app/Playlists/GET_USER_PLAYLISTS_FAILURE';

//GET BY ID
export const GET_AWS_PLAYLIST_START = 'app/Playlists/GET_AWS_PLAYLIST_START';
export const GET_AWS_PLAYLIST_SUCCESS = 'app/Playlists/GET_AWS_PLAYLIST_SUCCESS';
export const GET_AWS_PLAYLIST_FAILURE = 'app/Playlists/GET_AWS_PLAYLIST_FAILURE';

//POST
export const POST_AWS_PLAYLIST_START = 'app/Playlists/POST_AWS_PLAYLIST_START';
export const POST_AWS_PLAYLIST_SUCCESS = 'app/Playlists/POST_AWS_PLAYLIST_SUCCESS';
export const POST_AWS_PLAYLIST_FAILURE = 'app/Playlists/POST_AWS_PLAYLIST_FAILURE';

//PUT
export const PUT_AWS_PLAYLIST_START = 'app/Playlists/PUT_AWS_PLAYLIST_START';
export const PUT_AWS_PLAYLIST_SUCCESS = 'app/Playlists/PUT_AWS_PLAYLIST_SUCCESS';
export const PUT_AWS_PLAYLIST_FAILURE = 'app/Playlists/PUT_AWS_PLAYLIST_FAILURE';

//DELETE
export const DELETE_AWS_PLAYLIST_START = 'app/Playlists/DELETE_AWS_PLAYLIST_START';
export const DELETE_AWS_PLAYLIST_SUCCESS = 'app/Playlists/DELETE_AWS_PLAYLIST_SUCCESS';
export const DELETE_AWS_PLAYLIST_FAILURE = 'app/Playlists/DELETE_AWS_PLAYLIST_FAILURE';