export const SEARCH_MOVIE_START = 'SEARCH_MOVIE_START';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_COMPLETE = 'SEARCH_MOVIE_COMPLETE';
export const SEARCH_MOVIE_RESET = 'SEARCH_MOVIE_RESET';

export const SEARCH_MOVIE_BY_ID_START = 'SEARCH_MOVIE_BY_ID_START';
export const SEARCH_MOVIE_BY_ID_ERROR = 'SEARCH_MOVIE_BY_ID_ERROR';
export const SEARCH_MOVIE_BY_ID_COMPLETE = 'SEARCH_MOVIE_BY_ID_COMPLETE';
export const SEARCH_MOVIE_BY_ID_RESET = 'SEARCH_MOVIE_BY_ID_RESET';
