//AWS METODOS
//GET
//GET BY ID
export const GET_AWS_FOLDERS_START = 'app/Folders/GET_AWS_FOLDERS_START';
export const GET_AWS_FOLDERS_SUCCESS = 'app/Folders/GET_AWS_FOLDERS_SUCCESS';
export const GET_AWS_FOLDERS_FAILURE = 'app/Folders/GET_AWS_FOLDERS_FAILURE';

//POST
export const POST_AWS_FOLDERS_START = 'app/Folders/POST_AWS_FOLDERS_START';
export const POST_AWS_FOLDERS_SUCCESS = 'app/Folders/POST_AWS_FOLDERS_SUCCESS';
export const POST_AWS_FOLDERS_FAILURE = 'app/Folders/POST_AWS_FOLDERS_FAILURE';

//PUT
export const PUT_AWS_FOLDERS_START = 'app/Folders/PUT_AWS_FOLDERS_START';
export const PUT_AWS_FOLDERS_SUCCESS = 'app/Folders/PUT_AWS_FOLDERS_SUCCESS';
export const PUT_AWS_FOLDERS_FAILURE = 'app/Folders/PUT_AWS_FOLDERS_FAILURE';

//DELETE
export const DELETE_AWS_FOLDERS_START = 'app/Folders/DELETE_AWS_FOLDERS_START';
export const DELETE_AWS_FOLDERS_SUCCESS = 'app/Folders/DELETE_AWS_FOLDERS_SUCCESS';
export const DELETE_AWS_FOLDERS_FAILURE = 'app/Folders/DELETE_AWS_FOLDERS_FAILURE';

export const CLEAN_FOLDER = 'app/Folders/CLEAN_FOLDERS';