//AWS METODOS
//GET
export const GET_AWS_SONGS_START = 'app/Songs/GET_AWS_SONGS_START';
export const GET_AWS_SONGS_SUCCESS = 'app/Songs/GET_AWS_SONGS_SUCCESS';
export const GET_AWS_SONGS_FAILURE = 'app/Songs/GET_AWS_SONGS_FAILURE';

//POST
export const POST_AWS_SONGS_START = 'app/Songs/POST_AWS_SONGS_START';
export const POST_AWS_SONGS_SUCCESS = 'app/Songs/POST_AWS_SONGS_SUCCESS';
export const POST_AWS_SONGS_FAILURE = 'app/Songs/POST_AWS_SONGS_FAILURE';

//PUT
export const PUT_AWS_SONGS_START = 'app/Songs/PUT_AWS_SONGS_START';
export const PUT_AWS_SONGS_SUCCESS = 'app/Songs/PUT_AWS_SONGS_SUCCESS';
export const PUT_AWS_SONGS_FAILURE = 'app/Songs/PUT_AWS_SONGS_FAILURE';

//DELETE
export const DELETE_AWS_SONGS_START = 'app/Songs/DELETE_AWS_SONGS_START';
export const DELETE_AWS_SONGS_SUCCESS = 'app/Songs/DELETE_AWS_SONGS_SUCCESS';
export const DELETE_AWS_SONGS_FAILURE = 'app/Songs/DELETE_AWS_SONGS_FAILURE';

export const CLEAN_PLAYLIST = 'app/Playlists/CLEAN_PLAYLIST';
export const CLEAN_SONG = 'app/Playlists/CLEAN_SONG';