export const GET_RECENTLY_PLAYED_START =
  'app/Dashboard/GET_RECENTLY_PLAYED_START';
export const GET_RECENTLY_PLAYED_SUCCESS =
  'app/Dashboard/GET_RECENTLY_PLAYED_SUCCESS';
export const GET_RECENTLY_PLAYED_FAILURE =
  'app/Dashboard/GET_RECENTLY_PLAYED_FAILURE';
